export const COMMON_FIELDS = {
  unfactored: [
    {
      id: "DL",
      label: "Gk",
      type: "number",
      placeholder: "e.g. 500",
      unit: "kN",
      tooltip: "Permanent Load (Gk) - Unfactored permanent vertical load",
      required: true,
      min: 0,
    },
    {
      id: "LL",
      label: "Qk",
      type: "number",
      placeholder: "e.g. 300",
      unit: "kN",
      tooltip: "Variable Load (Qk) - Unfactored variable vertical load",
      required: true,
      min: 0,
    },
    {
      id: "mxp",
      label: "Moment X Permanent",
      type: "number",
      placeholder: "e.g. 50",
      unit: "kN-m",
      tooltip: "Moment X Permanent - Unfactored permanent moment about X-axis",
      required: true,
    },
    {
      id: "mxv",
      label: "Moment X Variable",
      type: "number",
      placeholder: "e.g. 30",
      unit: "kN-m",
      tooltip: "Moment X Variable - Unfactored variable moment about X-axis",
      required: true,
    },
    {
      id: "myp",
      label: "Moment Y Permanent",
      type: "number",
      placeholder: "e.g. 50",
      unit: "kN-m",
      tooltip: "Moment Y Permanent - Unfactored permanent moment about Y-axis",
      required: true,
    },
    {
      id: "myv",
      label: "Moment Y Variable",
      type: "number",
      placeholder: "e.g. 30",
      unit: "kN-m",
      tooltip: "Moment Y Variable - Unfactored variable moment about Y-axis",
      required: true,
    },
  ],
  factored: [
    {
      id: "NED",
      label: "Design Axial Load",
      type: "number",
      placeholder: "e.g. 1200",
      unit: "kN",
      tooltip: "Factored design axial load (NEd)",
      required: true,
      min: 0,
    },
    {
      id: "MXED",
      label: "Design Moment X",
      type: "number",
      placeholder: "e.g. 150",
      unit: "kN-m",
      tooltip: "Factored design moment about X-axis (Mx,Ed)",
      required: true,
    },
    {
      id: "MYED",
      label: "Design Moment Y",
      type: "number",
      placeholder: "e.g. 150",
      unit: "kN-m",
      tooltip: "Factored design moment about Y-axis (My,Ed)",
      required: true,
    }
  ]
};

export const MATERIAL_FIELDS = [
  {
    id: "FCK",
    label: "Concrete Strength",
    type: "number",
    placeholder: "e.g. 25",
    unit: "MPa",
    tooltip: "Concrete Strength - Characteristic compressive strength",
    required: true,
    min: 20,
    max: 60,
  },
  {
    id: "FYK",
    label: "Steel Strength",
    type: "number",
    placeholder: "e.g. 500",
    unit: "MPa",
    tooltip: "Steel Strength - Characteristic yield strength",
    required: true,
    min: 400,
    max: 600,
  },
  {
    id: "BAR",
    label: "Rebar Diameter",
    type: "number",
    placeholder: "e.g. 16",
    unit: "mm",
    tooltip: "Rebar Diameter - Main reinforcement bar size",
    required: true,
    min: 8,
    max: 32,
  },
  {
    id: "COV",
    label: "Concrete Cover",
    type: "select",
    options: [
      { value: "40", label: "40 mm (Footing on lean concrete)" },
      { value: "75", label: "75 mm (Footing on soil)" },
    ],
    tooltip: "Concrete Cover - Nominal concrete cover to reinforcement",
    required: true,
  },
];

export const GEOMETRY_FIELDS = {
  isolated: [
    {
      id: "COL",
      label: "Column Width X",
      type: "number",
      placeholder: "e.g. 300",
      unit: "mm",
      tooltip: "Column Width X - Column dimension along X-axis",
      required: true,
      min: 100,
    },
    {
      id: "COLY",
      label: "Column Width Y",
      type: "number",
      placeholder: "e.g. 300",
      unit: "mm",
      tooltip: "Column Width Y - Column dimension along Y-axis",
      required: true,
      min: 100,
    },
  ],
  combined: [
    {
      id: "COL1",
      label: "Column 1 Width X",
      type: "number",
      placeholder: "e.g. 300",
      unit: "mm",
      tooltip: "Column 1 Width X - First column X dimension",
      required: true,
      min: 100,
    },
    {
      id: "COLY1",
      label: "Column 1 Width Y",
      type: "number",
      placeholder: "e.g. 300",
      unit: "mm",
      tooltip: "Column 1 Width Y - First column Y dimension",
      required: true,
      min: 100,
    },
    {
      id: "COL2",
      label: "Column 2 Width X",
      type: "number",
      placeholder: "e.g. 300",
      unit: "mm",
      tooltip: "Column 2 Width X - Second column X dimension",
      required: true,
      min: 100,
    },
    {
      id: "COLY2",
      label: "Column 2 Width Y",
      type: "number",
      placeholder: "e.g. 300",
      unit: "mm",
      tooltip: "Column 2 Width Y - Second column Y dimension",
      required: true,
      min: 100,
    },
    {
      id: "COL_SPACING",
      label: "Column Spacing",
      type: "number",
      placeholder: "e.g. 3000",
      unit: "mm",
      tooltip: "Column Spacing - Distance between column centers",
      required: true,
      min: 500,
    },
  ],
  strap: [
    {
      id: "COL_MAIN",
      label: "Main Column Width",
      type: "number",
      placeholder: "e.g. 400",
      unit: "mm",
      tooltip: "Main Column Width - Primary column dimension",
      required: true,
      min: 100,
    },
    {
      id: "COL_STRAP",
      label: "Strap Column Width",
      type: "number",
      placeholder: "e.g. 300",
      unit: "mm",
      tooltip: "Strap Column Width - Secondary column dimension",
      required: true,
      min: 100,
    },
    {
      id: "STRAP_LENGTH",
      label: "Strap Beam Length",
      type: "number",
      placeholder: "e.g. 2500",
      unit: "mm",
      tooltip: "Strap Beam Length - Distance between columns",
      required: true,
      min: 500,
    },
  ],
  retaining: [
    {
      id: "WALL_HEIGHT",
      label: "Wall Height",
      type: "number",
      placeholder: "e.g. 2000",
      unit: "mm",
      tooltip: "Wall Height - Total wall height",
      required: true,
      min: 500,
    },
    {
      id: "WALL_THICKNESS",
      label: "Wall Thickness",
      type: "number",
      placeholder: "e.g. 300",
      unit: "mm",
      tooltip: "Wall Thickness - Base thickness of wall",
      required: true,
      min: 100,
    },
    {
      id: "TOE_LENGTH",
      label: "Toe Length",
      type: "number",
      placeholder: "e.g. 1000",
      unit: "mm",
      tooltip: "Toe Length - Length of toe extension",
      required: true,
      min: 300,
    },
    {
      id: "HEEL_LENGTH",
      label: "Heel Length",
      type: "number",
      placeholder: "e.g. 1500",
      unit: "mm",
      tooltip: "Heel Length - Length of heel extension",
      required: true,
      min: 300,
    },
  ],
};

export const SOIL_FIELDS = {
  CU: [
    {
      id: "DF",
      label: "Foundation Depth",
      type: "number",
      placeholder: "e.g. 1500",
      unit: "mm",
      tooltip:
        "Foundation Depth - Depth from ground surface to footing base",
      required: true,
      min: 300,
    },
    {
      id: "CU",
      label: "Undrained Cohesion",
      type: "number",
      placeholder: "e.g. 50",
      unit: "kPa",
      tooltip: "Undrained Cohesion - Soil undrained shear strength",
      required: true,
      min: 10,
    },
    {
      id: "GAM",
      label: "Soil Unit Weight",
      type: "number",
      placeholder: "e.g. 18",
      unit: "kN/m³",
      tooltip: "Soil Unit Weight - Unit weight of soil",
      required: true,
      min: 15,
      max: 22,
    },
  ],
  CD: [
    {
      id: "DF",
      label: "Foundation Depth",
      type: "number",
      placeholder: "e.g. 1500",
      unit: "mm",
      tooltip:
        "Foundation Depth - Depth from ground surface to footing base",
      required: true,
      min: 300,
    },
    {
      id: "C_PRIME",
      label: "Effective Cohesion",
      type: "number",
      placeholder: "e.g. 5",
      unit: "kPa",
      tooltip: "Effective Cohesion - Effective cohesion parameter",
      required: true,
      min: 0,
    },
    {
      id: "PHI_PRIME",
      label: "Friction Angle",
      type: "number",
      placeholder: "e.g. 25",
      unit: "°",
      tooltip: "Friction Angle - Effective angle of internal friction",
      required: true,
      min: 0,
      max: 45,
    },
    {
      id: "GAM",
      label: "Soil Unit Weight",
      type: "number",
      placeholder: "e.g. 18",
      unit: "kN/m³",
      tooltip: "Soil Unit Weight - Unit weight of soil",
      required: true,
      min: 15,
      max: 22,
    },
  ],
  S: [
    {
      id: "DF",
      label: "Foundation Depth",
      type: "number",
      placeholder: "e.g. 1500",
      unit: "mm",
      tooltip:
        "Foundation Depth - Depth from ground surface to footing base",
      required: true,
      min: 300,
    },
    {
      id: "PHI_PRIME",
      label: "Friction Angle",
      type: "number",
      placeholder: "e.g. 30",
      unit: "°",
      tooltip: "Friction Angle - Effective angle of internal friction",
      required: true,
      min: 25,
      max: 40,
    },
    {
      id: "GAM",
      label: "Soil Unit Weight",
      type: "number",
      placeholder: "e.g. 18",
      unit: "kN/m³",
      tooltip: "Soil Unit Weight - Unit weight of soil",
      required: true,
      min: 15,
      max: 22,
    },
  ],
  CUST: [
    {
      id: "BC",
      label: "Bearing Capacity",
      type: "number",
      placeholder: "e.g. 200",
      unit: "kPa",
      tooltip: "Bearing Capacity - Allowable bearing capacity",
      required: true,
      min: 50,
    },
    {
      id: "DF",
      label: "Foundation Depth",
      type: "number",
      placeholder: "e.g. 1500",
      unit: "mm",
      tooltip:
        "Foundation Depth - Depth from ground surface to footing base",
      required: true,
      min: 300,
    },
    {
      id: "GAM",
      label: "Soil Unit Weight",
      type: "number",
      placeholder: "e.g. 18",
      unit: "kN/m³",
      tooltip: "Soil Unit Weight - Unit weight of soil",
      required: true,
      min: 15,
      max: 22,
    },
  ],
};
